spring.application.name=padel-backend

# Database MySQL — plataforma_padel (Local o Nube)
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/plataforma_padel?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:}

# JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server configuration
server.port=${PORT:8080}

# Disable static resource caching
spring.web.resources.cache.period=0
