spring.application.name=padel-backend

# Database MySQL — plataforma_padel
spring.datasource.url=jdbc:mysql://localhost:3306/plataforma_padel?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=

# JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Server configuration
server.port=8080

# Disable static resource caching
spring.web.resources.cache.period=0
